server {
    listen 8082;
    server_name localhost;
    root test/www;
    index index.html;

    location / {
        allow_methods GET POST;
    }

    location /cgi-bin {
        allow_methods GET POST;
        root test/www;
        cgi_extension .py .php;
        cgi_path .py /usr/bin/python3;
        cgi_path .php /usr/bin/php-cgi;
    }

    location /upload {
        allow_methods GET POST DELETE;
        upload_enable on;
        upload_store test/www/upload;
    }
}
