server {
	listen 8080;
	server_name localhost;
	root test/www/site-localhost;
	index index.html;
	client_max_body_size 10485760;
	error_page 404 test/www/errors/404.html;

	location / {
		root test/www/site-localhost;
	}

	location /upload {
		allow_methods GET POST DELETE;
		upload_enable on;
		upload_store test/www/upload;
		client_max_body_size 500000000;
		error_page 404 test/www/errors/upload_error.html;
	}
}

server {
	listen 0.0.0.0:8080;

	server_name www.example.com mytest.local;
	root test/www/site-www-example;
	index index.html index.htm;

	client_max_body_size 10485760;

	error_page 404 test/www/errors/404.html;
	error_page 500 502 503 504 test/www/errors/50x.html;

	location / {
		allow_methods GET;
		root test/www/site-www-example;
		index index.html index.htm;
		autoindex on;
	}

	location /old-page {
		return 301 /new-page.html;
	}

	location /kapouet {
		allow_methods GET;
		alias test/www/kapouet;
	}

	location /upload {
		allow_methods GET POST DELETE;
		upload_enable on;
		upload_store test/www/upload;
	}

	location /cgi-bin {
		allow_methods GET POST;
		root test/www;
		cgi_extension .py .php;
		cgi_path .py /usr/bin/python3;
		cgi_path .php /usr/bin/php-cgi;
	}
}

server {
	listen 0.0.0.0:8080;
	server_name example.com;
	root test/www/site-example;
	index index.html;
	client_max_body_size 1024;
	location / {
		allow_methods GET;
		root test/www/site-example;
		index index.html;
	}
}

server {
	listen 0.0.0.0:8081;
	server_name webserv.local;
	root test/www/site-webserv-local;
	index index.html;
	location / {
		allow_methods GET;
		root test/www/site-webserv-local;
	}
}
