server {
	listen 172.19.0.2:8080;
	server_name localhost;
	root test/www;
	index index.html;

	location / {
		allow_methods GET;
	}
}

server {
	listen localhost:8082;
	server_name localhost2;
	root test/www;
	index index.html;

	location / {
		allow_methods GET;
	}
}

server {
	listen 127.0.0.1:8081;
	server_name all_ips;
	root test/www/site-webserv-local;
	index index.html;

	location / {
		allow_methods GET;
	}
}
