server {
	listen 8000;
	server_name localhost;
	root test/www;
	index index.html;
	client_max_body_size 1000000000;

	location / {
		allow_method GET;
		cgi_extension .bla;
		cgi_path .bla /app/cgi_tester;
	}

	location /post_body {
		allow_method POST;
		client_max_body_size 100;
	}

	location /directory {
		allow_method GET POST;
		alias test/YoupiBanane/;
		index youpi.bad_extension;
		cgi_extension .bla;
		cgi_path .bla /app/cgi_tester;
		client_max_body_size 1000000000;
	}

	location .bla {
		allow_method POST;
		cgi_extension .bla;
		cgi_path .bla /app/cgi_tester;
		client_max_body_size 1000000000;
	}
}
