server {
	listen 8080;
	server_name example.com;

	location / {
		allow_method GET;
		root test/www;
		index index.html;
	}

	location /cgi-bin {
		allow_methods GET POST;
		root test;
		cgi_extension .py .php;
		cgi_path .py /usr/bin/python3;
		cgi_path .php /usr/bin/php-cgi;
	}
}
