server {
	listen 8080;
	server_name localhost;

	location / {
		allow_method GET POST DELETE;
		root test/www;
		index index.html;
	}

	location /cgi-bin {
		allow_methods GET POST;
		root test;
		cgi_extension .py .php;
		cgi_path .py /usr/bin/python3;
		cgi_path .php /usr/bin/php-cgi;
	}
}

server {
	listen 8080;
	server_name localhost;
	client_max_body_size 10485760;
	error_page 404 /404.html;

	location / {
		root /var/www/html;
	}

	location /upload {
		upload_enable on;
		client_max_body_size 500000000;
		error_page 404 /upload_error.html;
	}
}
