server {
    listen 8080;
    server_name localhost;
    root www;
    index home.html fallback.html;
    client_max_body_size 2k;
    error_page 404 www/errors/404.html;

    location / {
        allow_method GET;
    }

    location /default {
    }

    location /upload {
        allow_methods GET POST DELETE;
        upload_enable on;
        upload_store tmp_upload;
        client_max_body_size 4k;
    }

    location /cgi-bin {
        allow_methods GET POST;
        root www;
        cgi_extension .py .php;
        cgi_path .py /usr/bin/python3;
        cgi_path .php /usr/bin/php-cgi;
    }

    location /old {
        return 301 /new;
    }

    location /files {
        allow_methods GET DELETE;
        alias /srv/files;
    }

    location /list {
        allow_method GET;
        autoindex on;
    }
}
