server {
    listen 8181;
    server_name localhost;
    root www;
    index index.html;
    error_page 404 www/errors/404.html;

    location / {
        allow_method GET;
    }

    location /auto {
        allow_method GET;
        autoindex on;
    }

    location /upload {
        allow_methods GET POST DELETE;
        upload_enable on;
        upload_store tmp_upload;
    }

    location /files {
        allow_methods GET DELETE;
        root www;
    }

    location /old {
        return 302 /new;
    }

    location /cgi-bin {
        allow_methods GET POST;
        root www;
        cgi_extension .py;
        cgi_path .py /usr/bin/python3;
    }
}
