server {
    listen 8080;
    root /var/www/html;
    location / {
        allow_method GET;
    }
    location /api {
        allow_method GET POST;
    }
    location /api/v2 {
        allow_method GET POST;
    }
}
