server {
    listen 8080;
    location / {
        allow_method GET;
        root /var/www/html;
    }
}

server {
    listen 9090;
    location / {
        allow_method GET;
        root /var/www/html;
    }
}
