server {
    listen 8080;
    server_name site-a.com;
    location / {
        allow_method GET;
        root /var/www/html;
    }
}

server {
    listen 8080;
    server_name site-b.com;
    location / {
        allow_method GET;
        root /var/www/html;
    }
}
