server {
    listen 127.0.0.1:8124;
    server_name same-port-a.local;
    location / {
        allow_method GET;
        root www;
    }
}

server {
    listen 127.0.0.2:8124;
    server_name same-port-b.local;
    location / {
        allow_method GET;
        root www;
    }
}
